In [1]:
import numpy as np
import pandas as pd

In [2]:
list_ = [1,2,3,4,5]
array_list=np.array(object=list_)

In [3]:
array_list

array([1, 2, 3, 4, 5])

In [6]:
type(array_list)

numpy.ndarray

In [8]:
list_

[1, 2, 3, 4, 5]

In [9]:
type(list_)

list

In [11]:
# Ans1
print=('variables list_ is a list itself while array_list is ndarray as illustrated in above code')
print

'variables list_ is a list itself while array_list is ndarray as illustrated in above code'

In [13]:
#Ans2
type(list_)

list

In [14]:
type(array_list)

numpy.ndarray

In [15]:
# Ans3
array_list=np.array(object=list_, dtype=int)

In [16]:
array_list

array([1, 2, 3, 4, 5])

In [17]:
array_list.dtype

dtype('int64')

In [19]:
type(array_list)

numpy.ndarray

In [20]:
type(list_)

list

In [23]:
# Ans4
num_list=[[1,2,3],[4,5,6]]
num_array=np.array(object=num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
num_array.shape

(2, 3)

In [25]:
num_array.size

6

In [28]:
# Asn5
zero_array=np.zeros((3,3))

In [29]:
zero_array.size

9

In [30]:
zero_array.shape

(3, 3)

In [36]:
# Ans6
array1=np.eye(5)
array1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
array1.shape

(5, 5)